// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.

#import <stdio.h>

int main(void) {

    int a, b, c, sum, max;

    a = 1;
    b = 1;
    c = 0;
    sum = 0;
    max = 4000000;
    while (c < max) {
        c = a + b;
        a = b;
        b = c;
        if(!(b%2))
            sum+=b;
    } 

    printf("The sum is %d", sum);
}


